version: "3"
services:
    web:
        build: ./app
        command: pipenv run python manage.py runserver 0.0.0.0:8000
        volumes:
          - ./app/:/usr/src/app/
        ports:
          - 8000:8000
        env_file:
          - ./.env.dev
        depends_on:
            - database
    database:
        image: postgres:12.0-alpine
        volumes:
            - psql-data:/var/lib/postgresql/data
        environment:
          - POSTGRES_DB=hello_django_dev
          - POSTGRES_USER=hello_django
          - POSTGRES_PASSWORD=hello_django
        ports:
            - '5432:5432'

volumes:
  psql-data:
