version: "3.8"


services:
    camera:
        command: python alarm.py
        env_file:
            - .env
        networks:
            - backend_mqtt
            - motion
        # Give access to the rpi camera device.
        privileged: true
        environment:
                - LD_LIBRARY_PATH=/opt/vc/lib
        volumes:
            - camera_videos/:/var/lib/camera/media
            - tf-models/:/var/lib/camera/tf-models
            - /opt/vc:/opt/vc

        devices:
                - "/dev/vchiq:/dev/vchiq"

    sound:
        command: python sound.py
        env_file:
            - .env
        networks:
            - backend_mqtt
            - motion
        # Give access to the rpi audio device. Otherwise it cannot play sound! see issue #126
        privileged: true


networks:
    motion:
        name: motion
    backend_mqtt:
        external:
            name: backend_mqtt

volumes:
    camera_videos:
        external: true
    tf-models:
        driver: local
