version: "3.8"


x-logging: &loki-logging
    driver: loki
    options:
        loki-url: "http://loki:3100/api/prom/push"


services:
    camera:
        image: mxmaxime/camera:0.2.2
        logging: *loki-logging

    sound:
        image: mxmaxime/camera:0.2.2
        logging: *loki-logging

    listen_frame:
        image: mxmaxime/camera:0.2.2
        logging: *loki-logging
