version: "3.8"


x-logging: &loki-logging
    driver: loki
    options:
        loki-url: "http://localhost:3100/api/prom/push"


services:
    camera:
        image: mxmaxime/camera:0.2.2
        logging: *loki-logging
        restart: unless-stopped

    sound:
        image: mxmaxime/camera:0.2.2
        logging: *loki-logging
        restart: unless-stopped

    listen_frame:
        image: mxmaxime/camera:0.2.2
        logging: *loki-logging
        restart: unless-stopped
