version: "3.8"


x-logging: &loki-logging
    driver: loki
    options:
        loki-url: "http://localhost:3100/api/prom/push"

services:
    camera:
        logging: *loki-logging

    sound:
        logging: *loki-logging
