version: "3.8"


services:
    camera:
        build: ./app
        command: bash -c "chmod +x ./scripts/wait-for-it.sh && ./scripts/wait-for-it.sh -t 0 mqtt_broker:8883 -- python alarm.py"
        env_file:
            - .env
        networks: 
            - backend_mqtt
            - motion

        # Give access to the rpi camera device.
        privileged: true
        environment:
                - LD_LIBRARY_PATH=/opt/vc/lib
        volumes:
            - ./app/:/usr/src/app/
            - /opt/vc:/opt/vc

        devices:
                - "/dev/vchiq:/dev/vchiq"

    sound:
        build: ./app
        command: bash -c "chmod +x ./scripts/wait-for-it.sh && ./scripts/wait-for-it.sh -t 0 mqtt_broker:8883 -- python sound.py"
        env_file:
            - .env
        networks:
            - backend_mqtt
            - motion


networks:
    motion:
        name: motion
    backend_mqtt:
        external:
            name: backend_mqtt
