version: '3.7'

x-build: &build
    build:
        context: ./app
        args:
            USER_ID: ${USER_ID}
            GROUP_ID: ${GROUP_ID}

x-env: &env
    env_file:
        - .env.test

services:
    mqtt_broker:
        volumes:
            - ./config/mosquitto/mosquitto-test.conf:/mosquitto/config/mosquitto.conf
            - ./config/mosquitto/test-passwd:/mosquitto/config/passwd

    celery_worker:
        <<: *build
        <<: *env
        volumes:
            - ./app/:/usr/src/app/

    celery_beat:
        <<: *build
        <<: *env
        volumes:
            - ./app/:/usr/src/app/

    web:
        <<: *build
        <<: *env
        volumes:
            - ./app/:/usr/src/app/

    python_process_mqtt:
        <<: *build
        <<: *env
        volumes:
            - ./app/:/usr/src/app/

    telegram_bot:
        <<: *build
        <<: *env
        volumes:
            - ./app/:/usr/src/app/

