version: '3.8'


x-build: &build
    build:
        context: ./app
        args:
            USER_ID: ${USER_ID}
            GROUP_ID: ${GROUP_ID}

x-env: &env
    env_file:
        - .env
        - ~/.device

services:
    redis-broker:
        volumes:
            - dev-redis-broker-data:/data
    database:
        volumes:
            - dev-psql-data:/var/lib/postgresql/data

    celery_worker:
        <<: *build
        <<: *env
        volumes:
            - ./app/:/usr/src/app/

    celery_beat:
        <<: *build
        <<: *env
        volumes:
            - ./app/:/usr/src/app/

    web:
        <<: *build
        <<: *env
        volumes:
            - ./app/:/usr/src/app/

    python_process_mqtt:
        <<: *build
        <<: *env
        volumes:
            - ./app/:/usr/src/app/

    telegram_bot:
        <<: *build
        <<: *env
        volumes:
            - ./app/:/usr/src/app/

    node:
        user: '${USER_ID}:${GROUP_ID}'
        build:
            context: ./tools/docker/node
        command: npm run dev
        working_dir: /usr/src/app
        volumes:
            - ./app:/usr/src/app
        ports:
            - 3000:3000
    vim:
      build:
        context: ./tools/docker/dev
      volumes:
        - ~/.vim/:/home/house/.vim/
        - ~/.config/coc/:/home/house/.config/coc
        - ~/.vimrc/:/home/house/.vimrc
        - ./app/:/usr/src/app/
      command: bash -c "source /home/house/.nvm/nvm.sh && node -v && vim"
      networks:
        - redis-broker
        - webapp_backend
        - backend_mqtt

volumes:
    dev-redis-broker-data:
        driver: local
    dev-psql-data:
        driver: local
