version: "3.8"


services:
    redis-broker:
        image: redis:6.2-buster
        ports:
            - "6379:6379"
        networks:
            - redis-broker
            - backend_mqtt
        volumes:
            - ./config/redis/redis-broker.conf:/usr/local/etc/redis/redis.conf

    database:
        image: postgres:13.1
        environment:
          - POSTGRES_DB=hello_django_dev
          - POSTGRES_USER=hello_django
          - POSTGRES_PASSWORD=hello_django
        ports:
            - '5432:5432'
        networks:
            - webapp_backend

    mqtt_broker:
        image: eclipse-mosquitto:2.0.10
        volumes:
            - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./config/mosquitto/passwd:/mosquitto/config/passwd
            - mosquitto-data:/mosquitto/data
        ports:
            - "8883:8883"
        networks:
            - webapp_backend
            - backend_mqtt

    celery_worker:
        command: bash -c "celery -A hello_django worker --autoscale=2,1 --loglevel=INFO"
        volumes:
            - camera_videos:/var/lib/house/video
            - medias:/var/lib/house/media
            - ~/.ssh:/home/house/.ssh:ro # for rsync to get videos from dumb devices.
        networks:
            - webapp_backend
            - redis-broker
            - backend_mqtt
        depends_on:
            - redis-broker
            - database
            - mqtt_broker

    celery_beat:
        command: bash -c "rm -f celerybeat.pid && celery -A hello_django beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=info --pidfile="
        networks:
            - redis-broker
            - backend_mqtt
            - webapp_backend
        depends_on:
            - redis-broker
            - database
            - mqtt_broker

    web:
        command: bash -c "python manage.py migrate --no-input && python register_device.py && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - medias:/var/lib/house/media
            - devices:/var/lib/house/devices
        ports:
          - 8000:8000
        depends_on:
            - database
            - mqtt_broker
            - celery_worker
            - celery_beat
        networks:
            redis-broker:
            webapp_backend:
            backend_mqtt:

    python_process_mqtt:
        command: bash -c "python standalone/mqtt/mqtt_run.py"
        volumes:
            - medias:/var/lib/house/media
        depends_on:
            - celery_worker
            - database
        networks:
            redis-broker:
            webapp_backend:
            backend_mqtt:

    telegram_bot:
        command: python standalone/telegram_bot/bot.py
        depends_on:
            - database
            - celery_worker
        networks:
            - redis-broker
            - webapp_backend
            - backend_mqtt

networks:
    redis-broker:
    webapp_backend:
    backend_mqtt:
        external: true

volumes:
    medias:
        driver: local
    devices:
        driver: local
    mosquitto-data:
        driver: local
    vim-plugins:
        driver: local
    camera_videos:
        external: true
