version: '3.6'

services:
  pihole:
    image: pihole/pihole:v5.6
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "4000:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Paris'
      WEBPASSWORD: 'super-secure-web-password'
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
