version: "3.8"


x-logging: &loki-logging
    driver: loki
    options:
        loki-url: "http://localhost:3100/api/prom/push"

services:
    py:
        build: ./app
        command: bash -c "chmod +x ./scripts/wait-for-it.sh && ./scripts/wait-for-it.sh -t 0 mqtt:8883 -- python alarm.py"
        env_file:
            - .env
        logging: *loki-logging
        networks: 
            - backend_mqtt
            - motion

        # Give access to the rpi camera device.
        privileged: true
        environment:
                - LD_LIBRARY_PATH=/opt/vc/lib
        volumes:
            - ./app/:/usr/src/app/
            - /opt/vc:/opt/vc

        devices:
                - "/dev/vchiq:/dev/vchiq"

networks:
    motion:
        name: motion
    backend_mqtt:
        external:
            name: backend_mqtt
