version: "3"
services:
    py:
        build: ./app
        command: pipenv run python mqtt.py
        env_file:
            - ./.env
        networks: 
            - webapp_backend
            - mqtt_server

networks:
    webapp_backend:
        external: 
            name: webapp_webapp_backend
    mqtt_server:
        external: 
            name: webapp_mqtt_server
