version: "3"
services:
    py:
        build: ./app
        command: pipenv run python send-alert.py
        env_file:
            - ./.env

networks:
    default:
        external: 
            name: webapp_webapp_backend
