version: "3.8"

x-env: &env
    env_file:
        - .env

x-logging: &loki-logging
    driver: loki
    options:
        loki-url: "http://localhost:3100/api/prom/push"

services:
    object_detection:
        image: bobbyhome/object-detection:0.0.2
        <<: *env
        logging: *loki-logging
        restart: unless-stopped
