version: "3.8"


x-logging: &loki-logging
    driver: loki
    options:
        loki-url: "http://localhost:3100/api/prom/push"


x-cameraimage: &cameraimage
    image: bobbyhome/camera:0.4.2


services:
    camera:
        <<: *cameraimage
        logging: *loki-logging
        restart: unless-stopped

    sound:
        <<: *cameraimage
        logging: *loki-logging
        restart: unless-stopped

    listen_frame:
        <<: *cameraimage
        logging: *loki-logging
        restart: unless-stopped
