version: "3.8"


x-env: &env
    env_file:
        - .env
        - ~/.device

services:
    camera:
        command: python camera.py
        <<: *env
        # Give access to the rpi camera device.
        privileged: true
        environment:
                - LD_LIBRARY_PATH=/opt/vc/lib
        volumes:
            - /opt/vc:/opt/vc
        devices:
                - "/dev/vchiq:/dev/vchiq"

    sound:
        command: python sound.py
        <<: *env
        # Give access to the rpi audio device. Otherwise it cannot play sound! see issue #126
        privileged: true

