version: "3.8"


x-logging: &loki-logging
    driver: loki
    options:
        loki-url: "http://localhost:3100/api/prom/push"


x-cameraimage: &cameraimage
    image: bobbyhome/camera:0.6.0


services:
    camera:
        <<: *cameraimage
        logging: *loki-logging
        restart: unless-stopped
        networks:
            - backend_mqtt
            - motion
        volumes:
            - camera_videos:/var/lib/camera/media

    sound:
        <<: *cameraimage
        logging: *loki-logging
        restart: unless-stopped
        networks:
            - backend_mqtt
            - motion

volumes:
    camera_videos:
        external: true

 networks:
    motion:
        name: motion
    backend_mqtt:
        external:
            name: backend_mqtt
