name: Run tests
on: [push]
jobs:
  test:
    name: Run core tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      #- name: Install buildx
      #  uses: docker/setup-buildx-action@v1.2.0
      #  id: buildx
      #  with:
      #    install: true
          
      - name: Run tests & generate coverage report
        run: |
            make coverage
            bash <(curl -s https://codecov.io/bash)

