version: "3"
services:
        camera:
                build: ./camera
                command: python3 motion.py
                # Give access to the rpi camera device.
                privileged: true
                environment:
                        - LD_LIBRARY_PATH=/opt/vc/lib
                volumes:
                        - ./camera/data:/usr/src/app/camera/data
                        - /opt/vc:/opt/vc
                devices:
                        - "/dev/vchiq:/dev/vchiq"
